[env:weact-esp32s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_speed = 115200
upload_port = COM8
board_upload.use_1200bps_touch = false
board_upload.wait_for_upload_port = true
upload_resetmethod = default

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUINO_USB_CDC_ON_BOOT=1
    -DTEST_SDA_PIN=10
    -DTEST_SCL_PIN=11
    -DTEST_XSHUT_PIN=9

; Use the standalone reference driver supplied for this sensor.
lib_extra_dirs = ../../DRIVER_ROBOTAAGV
