[env:weact-esp32s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
; Set this to the COM port shown by PlatformIO/Device Manager.
; upload_port = COM8
build_flags =
    -DCONFIG_ARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_ARDUINO_LOOP_TASK_STACK_SIZE=8192
