FROM ros:humble-ros-base

ENV DEBIAN_FRONTEND=noninteractive

# Cài đặt foxglove-bridge và slam-toolbox để nhận diện được các custom messages/services
RUN apt-get update && apt-get install -y --fix-missing --no-install-recommends \
  ros-humble-foxglove-bridge \
  ros-humble-slam-toolbox \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Chạy bridge khi khởi động
CMD ["ros2", "launch", "foxglove_bridge", "foxglove_bridge_launch.xml", "port:=8765"]