FROM ros:humble-ros-base

# Cài đặt foxglove-bridge trực tiếp từ kho của ROS 2
RUN apt-get update && apt-get install -y \
  ros-humble-foxglove-bridge \
  && rm -rf /var/lib/apt/lists/*

# Chạy bridge khi khởi động
CMD ["ros2", "launch", "foxglove_bridge", "foxglove_bridge_launch.xml", "port:=8765"]