services:
  # 1. Core mapping system (giữ nguyên)
  robot-core:
    build: .
    container_name: robot_core
    privileged: true
    volumes:
      - /dev:/dev
    environment:
      - ROS_DOMAIN_ID=0
    restart: always

  # 2. Cổng giao tiếp Web (Tự build để tương thích Pi 5)
  foxglove-bridge:
    build:
      context: .
      dockerfile: Dockerfile.foxglove
    container_name: foxglove_bridge
    ports:
      - "8888:8765"
    environment:
      - ROS_DOMAIN_ID=0
    restart: always