FROM ros:jazzy-ros-base

ENV DEBIAN_FRONTEND=noninteractive

# Cài đặt rosbridge-server và các gói bổ trợ cần thiết
RUN apt-get update && apt-get install -y --fix-missing --no-install-recommends \
  ros-jazzy-rosbridge-server \
  ros-jazzy-slam-toolbox \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Chạy rosbridge WebSocket server ở cổng 9090 khi khởi động
CMD ["ros2", "launch", "rosbridge_server", "rosbridge_websocket_launch.xml", "port:=9090"]
