'use client';

import { Alert, Card, Descriptions, Tag } from 'antd';
import { Gauge } from 'lucide-react';
import { DiagramPanel, MetricCard, TechnicalPageShell, TechnicalSection, TechnicalTable, type TechnicalTableRow } from '@/components/technical/TechnicalPageShell';
import EmaResponseChart from './EmaResponseChart';
import { EncoderArchitectureDiagram, OverflowDiagram, PidLoopDiagram, QuadratureDiagram, RpmPipelineDiagram, TimingAndTelemetryDiagram, WheelLayoutDiagram } from './EncoderDiagrams';

const createColumns = (first: string, fields: string[]) => [{ title: first, dataIndex: fields[0], key: fields[0] }, ...fields.slice(1).map((field) => ({ title: field, dataIndex: field, key: field }))];

const motorRows: TechnicalTableRow[] = [
  { key: 'voltage', parameter: 'Điện áp định mức', value: '12 V DC' }, { key: 'speed', parameter: 'Tốc độ không tải', value: '333 RPM motor shaft' }, { key: 'gear', parameter: 'Tỷ số hộp số', value: '30:1' }, { key: 'output', parameter: 'Output RPM', value: '333 / 30 ≈ 11.1 RPM' }, { key: 'ppr', parameter: 'Encoder resolution', value: '11 PPR × x2 = 22 counts/rev motor' }, { key: 'cpr', parameter: 'Output resolution', value: '660 counts/rev output' },
];
const pcntRows: TechnicalTableRow[] = [
  { key: 'units', parameter: 'PCNT units', value: '4 · UNIT_0..3' }, { key: 'signed', parameter: 'Counter width', value: 'int16_t signed · -32768..32767' }, { key: 'filter', parameter: 'Filter', value: '1000 ticks ≈ 12.5 µs @80 MHz' }, { key: 'decode', parameter: 'Decode mode', value: 'x2 · CHA edge + CHB direction' }, { key: 'aggregate', parameter: 'Aggregation', value: 'int32_t cumulative_count_' },
];
const summaryRows: TechnicalTableRow[] = [
  { key: 'hardware', layer: 'L1 Hardware', component: 'Hall Sensor', input: 'Magnetic rotation', output: 'CHA + CHB square waves', rate: '666 pulse/s @333 RPM', latency: '~1.5 ms debounce' }, { key: 'pcnt', layer: 'L2 PCNT', component: 'ESP32-S3 PCNT', input: 'Quadrature edges', output: 'int16 raw count', rate: 'Real-time hardware', latency: '~12.5 µs filter' }, { key: 'aggregate', layer: 'L3 Aggregate', component: 'Encoder::readCount()', input: 'Raw delta', output: 'int32 cumulative', rate: '50 Hz', latency: '~10 µs' }, { key: 'rpm', layer: 'L4 RPM', component: 'calculateRPM()', input: 'delta + dt', output: 'filtered RPM', rate: '50 Hz', latency: 'τ ≈ 56 ms' }, { key: 'pid', layer: 'L5 Control', component: 'PIDController', input: 'target + actual', output: 'PWM duty', rate: '50 Hz', latency: '~5 µs' }, { key: 'telemetry', layer: 'L5 Telemetry', component: 'JsonStatus::encoder()', input: '4× count/rpm', output: 'Type 130 JSON', rate: '20 Hz', latency: '~2 ms' },
];
const convergenceRows: TechnicalTableRow[] = [
  { key: '0', tick: '0', time: '0 ms', raw: '—', ema: '0.0', error: '100%', note: 'Khởi động' }, { key: '1', tick: '1', time: '20 ms', raw: '180', ema: '54.0', error: '73%', note: 'Cold start' }, { key: '2', tick: '2', time: '40 ms', raw: '200', ema: '97.8', error: '51%', note: '—' }, { key: '5', tick: '5', time: '100 ms', raw: '200', ema: '165.0', error: '17.5%', note: '—' }, { key: '9', tick: '9', time: '180 ms', raw: '200', ema: '191.6', error: '4.2%', note: '≈95% convergence' }, { key: '20', tick: '20', time: '400 ms', raw: '200', ema: '199.6', error: '0.2%', note: 'Steady state' },
];

export default function EncoderPipelinePage() {
  return <TechnicalPageShell eyebrow="Motor control / report 02" title="ENCODER PIPELINE" description="Từ Hall sensor ở mỗi motor qua PCNT ESP32-S3, xử lý RPM và PID, đến Type 130 telemetry cho Raspberry Pi 5 và ROS 2." icon={<Gauge size={14} />}>
    <div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Decode" value="x2" detail="CHA đếm, CHB quyết định hướng" /><MetricCard label="CPR output" value="660" detail="counts/rev sau gear 30:1" color="var(--success)" /><MetricCard label="EMA" value="α=0.3" detail="τ ≈ 56 ms · 95% ≈ 180 ms" color="var(--accent)" /><MetricCard label="Telemetry" value="Type 130" detail="4 motor × count + RPM · 20 Hz" color="var(--warning)" /></div>
    <TechnicalSection title="01 · Kiến trúc encoder và phần cứng"><DiagramPanel label="Encoder architecture" caption="Luồng encoder được xử lý hoàn toàn trong ESP32 trước khi telemetry đến Pi 5."><EncoderArchitectureDiagram /></DiagramPanel><div className="grid gap-4 lg:grid-cols-2"><TechnicalTable ariaLabel="Thông số motor encoder" columns={createColumns('Thông số motor', ['parameter', 'value'])} rows={motorRows} /><TechnicalTable ariaLabel="Thông số PCNT" columns={createColumns('Thông số PCNT', ['parameter', 'value'])} rows={pcntRows} /></div></TechnicalSection>
    <TechnicalSection title="02 · Quadrature và overflow"><DiagramPanel label="Quadrature signal" caption="PCNT x2 đếm cạnh lên Channel A; Channel B xác định chiều quay."><QuadratureDiagram /></DiagramPanel><DiagramPanel label="Overflow handling" caption="Counter 16-bit wrap được cộng dồn vào cumulative_count_ 32-bit."><OverflowDiagram /></DiagramPanel><Alert type="warning" showIcon title="Wraparound cần được đọc liên tục" description="Ở vận tốc cao, raw PCNT counter có thể tràn sau vài giây. Encoder::readCount() phải phát hiện wrap ±32768 để bảo toàn cumulative count." /></TechnicalSection>
    <TechnicalSection title="03 · Tính RPM và EMA filter"><DiagramPanel label="RPM pipeline" caption="Mỗi tick 20 ms tính delta, RPM raw, clamp, EMA và deadband trước PID."><RpmPipelineDiagram /></DiagramPanel><Card styles={{ body: { padding: 20 } }}><h3 className="mb-4 text-sm font-bold" style={{ color: 'var(--text-primary)' }}>Phản hồi EMA · step 0 → 300 RPM</h3><EmaResponseChart /><pre className="mt-5 overflow-x-auto rounded-lg p-4 text-xs leading-6" style={{ background: 'var(--bg-base)', color: 'var(--text-secondary)' }}>{`RPMₙ = RPMₙ₋₁ × (1 − α) + RPMraw × α\nτ = −Δt / ln(1−α) = −20ms / ln(0.7) ≈ 56ms\n95% hội tụ ≈ 3τ ≈ 168ms`}</pre></Card></TechnicalSection>
    <TechnicalSection title="04 · PID feedback và bố trí chassis"><DiagramPanel label="PID closed loop" caption="Feedback RPM đã lọc quay về nút lỗi của PID để điều chỉnh PWM BTS7960."><PidLoopDiagram /></DiagramPanel><DiagramPanel label="Wheel encoder layout" caption="Mỗi wheel dùng một PCNT unit và hai GPIO encoder độc lập."><WheelLayoutDiagram /></DiagramPanel></TechnicalSection>
    <TechnicalSection title="05 · Timing và telemetry"><DiagramPanel label="Timing and Type 130" caption="Encoder + RPM + PID chiếm dưới 0.1 ms của chu kỳ điều khiển 20 ms."><TimingAndTelemetryDiagram /></DiagramPanel><div className="grid gap-6 lg:grid-cols-[1fr_1.3fr]"><Card styles={{ body: { padding: 18 } }}><div className="flex items-center gap-2"><Tag color="gold">TYPE 130</Tag><span className="text-xs" style={{ color: 'var(--text-secondary)' }}>Encoder snapshot ESP32 → Pi</span></div><Descriptions className="mt-4" size="small" column={1} items={[{ key: 'frequency', label: 'Tần suất', children: '20 Hz · mỗi 50 ms' }, { key: 'size', label: 'Kích thước', children: '~250 bytes' }, { key: 'throughput', label: 'Throughput', children: '~5 KB/s' }, { key: 'payload', label: 'Payload', children: 'id · name · count · filtered rpm' }]} /></Card><TechnicalTable ariaLabel="Tổng hợp encoder pipeline" columns={createColumns('Layer', ['layer', 'component', 'input', 'output', 'rate', 'latency'])} rows={summaryRows} /></div></TechnicalSection>
    <TechnicalSection title="06 · Ví dụ FR chạy 200 RPM"><Card styles={{ body: { padding: 20 } }}><h3 className="text-sm font-bold" style={{ color: 'var(--text-primary)' }}>Numerical trace</h3><div className="mt-4 grid gap-3 text-xs md:grid-cols-2" style={{ color: 'var(--text-secondary)' }}>{[['01', 'Motor shaft', '200 output RPM × 30 = 6,000 RPM'], ['02', 'Encoder', '6,000 / 60 × 22 = 2,200 pulse/s'], ['03', 'PCNT delta', '2,200 × 0.020 = 44 count/tick'], ['04', 'RPM raw', '44 / 20 × 60,000 / 660 = 200.0 RPM'], ['05', 'EMA + PID', '≈200.0 RPM → error = 0'], ['06', 'Telemetry', '{"name":"FR","count":N,"rpm":200.0}']].map(([number, label, value]) => <div key={number} className="rounded-lg border p-3" style={{ borderColor: 'var(--border-dim)' }}><span className="font-mono text-[10px]" style={{ color: 'var(--accent)' }}>{number}</span><strong className="ml-2" style={{ color: 'var(--text-primary)' }}>{label}</strong><p className="mt-2 font-mono">{value}</p></div>)}</div></Card><TechnicalTable ariaLabel="EMA convergence at 200 RPM" columns={createColumns('Tick', ['tick', 'time', 'raw', 'ema', 'error', 'note'])} rows={convergenceRows} /></TechnicalSection>
  </TechnicalPageShell>;
}
