[env:weact-esp32s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -I include -I include/modules
    -DCONFIG_ESPTOOLPY_FLASHMODE_QIO=1
    -DCONFIG_ESPTOOLPY_FLASHFREQ_80M=1
    -DCONFIG_ESPTOOLPY_FLASHSIZE_16MB=1
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
    -DCONFIG_ARDUINO_EVENT_RUN_LOOP_CORE=0
    -DCONFIG_ARDUINO_EVENT_FORCE_RUN_LOOP=1
    -DCONFIG_ESP32S3_DEVKIT_JTAG_DISABLED=1
    -DCONFIG_JTAG_ENABLE=0
    -DCONFIG_ESP32S3_DEFAULT_CPU_FREQ_MHZ_240=1
    -DCONFIG_ESP32S3_PSRAM_SIZE=8MB
    -DCONFIG_ESP32S3_PSRAM_FREQ_80M=1
    -DCONFIG_SPIRAM=1
    -DCONFIG_SPIRAM_MODE_OCT=1
    -DCONFIG_ARDUINO_USB_CDC_ON_BOOT=0
    -DCONFIG_ARDUINO_LOOP_TASK_STACK_SIZE=16384

lib_deps =
    bblanchon/ArduinoJson@^7.2.0
